// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using San_Pham_Do_An1.Models;

#nullable disable

namespace San_Pham_Do_An1.Migrations
{
    [DbContext(typeof(WedQuanAoDbContext))]
    [Migration("20260731143316_Thao")]
    partial class Thao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbAccount", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"), 1L, 1);

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AccountId");

                    b.HasIndex("RoleId");

                    b.ToTable("tb_Account");

                    b.HasData(
                        new
                        {
                            AccountId = 1,
                            Email = "admin@example.com",
                            FullName = "ADMIN",
                            IsActive = true,
                            LastLogin = new DateTime(2026, 7, 18, 8, 23, 17, 451, DateTimeKind.Unspecified),
                            Password = "admin",
                            Phone = "0901000001",
                            RoleId = 1,
                            Username = "admin"
                        },
                        new
                        {
                            AccountId = 2,
                            Email = "editor@example.com",
                            FullName = "NHAN VIEN",
                            IsActive = true,
                            LastLogin = new DateTime(2026, 7, 9, 19, 45, 52, 183, DateTimeKind.Unspecified),
                            Password = "nhanvien",
                            Phone = "0901000002",
                            RoleId = 2,
                            Username = "nhanvien"
                        },
                        new
                        {
                            AccountId = 13,
                            Email = "hognviet@gmail.com",
                            FullName = "Viet Viet",
                            IsActive = true,
                            LastLogin = new DateTime(2026, 7, 27, 13, 11, 36, 924, DateTimeKind.Unspecified),
                            Password = "81dc9bdb52d04dc20036dbd8313ed055",
                            Phone = "0345472946",
                            RoleId = 1,
                            Username = "hognviet"
                        },
                        new
                        {
                            AccountId = 14,
                            Email = "son@gmail.com",
                            FullName = "Ngoo Son",
                            IsActive = true,
                            LastLogin = new DateTime(2026, 7, 5, 22, 58, 9, 615, DateTimeKind.Unspecified),
                            Password = "81dc9bdb52d04dc20036dbd8313ed055",
                            Phone = "0145678923",
                            RoleId = 2,
                            Username = "son"
                        });
                });

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbBlog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogId"), 1L, 1);

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Alias")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("BlogCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("BlogId");

                    b.HasIndex("AccountId");

                    b.HasIndex("BlogCategoryId");

                    b.ToTable("tb_Blog");

                    b.HasData(
                        new
                        {
                            BlogId = 1,
                            AccountId = 2,
                            BlogCategoryId = 1,
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 7, 4, 8, 36, 19, 421, DateTimeKind.Unspecified),
                            Description = "Nhưng xu hướng nổi bật 2025",
                            Image = "/assets/img/blog/blog1.png",
                            IsActive = true,
                            Title = "Xu hướng thời trang 2025"
                        },
                        new
                        {
                            BlogId = 2,
                            AccountId = 2,
                            Alias = "cach-phoi-do",
                            BlogCategoryId = 2,
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 7, 15, 14, 28, 42, 765, DateTimeKind.Unspecified),
                            Description = "Mẹo phối đồ",
                            Image = "/assets/img/blog/blog2.png",
                            IsActive = true,
                            Title = "Cách phối đồ cơ bản"
                        },
                        new
                        {
                            BlogId = 3,
                            AccountId = 2,
                            Alias = "huong-dan-nuoc-hoa",
                            BlogCategoryId = 4,
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 7, 25, 22, 49, 8, 233, DateTimeKind.Unspecified),
                            Description = "Nước hoa tự chế",
                            Image = "/assets/img/blog/blog3.png",
                            IsActive = true,
                            Title = "Hướng dẫn chưng cất nước hoa"
                        });
                });

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbBlogCategory", b =>
                {
                    b.Property<int>("BlogCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogCategoryId"), 1L, 1);

                    b.Property<string>("Alias")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("BlogCategoryId");

                    b.ToTable("tb_BlogCategory");

                    b.HasData(
                        new
                        {
                            BlogCategoryId = 1,
                            Alias = "thoi-trang",
                            CreatedDate = new DateTime(2026, 7, 2, 9, 14, 27, 318, DateTimeKind.Unspecified),
                            Description = "Tin tức về thời trang",
                            Image = "/assets/img/product/small-product1.png",
                            Title = "Thời trang"
                        },
                        new
                        {
                            BlogCategoryId = 2,
                            Alias = "meo-mac-dep",
                            CreatedDate = new DateTime(2026, 7, 8, 16, 42, 51, 604, DateTimeKind.Unspecified),
                            Description = "Hướng dẫn phối đồ",
                            Image = "/assets/img/product/small-product2.png",
                            Title = "Mẹo mặc đẹp"
                        },
                        new
                        {
                            BlogCategoryId = 3,
                            Alias = "khuyen-mai",
                            CreatedDate = new DateTime(2026, 7, 17, 20, 5, 36, 147, DateTimeKind.Unspecified),
                            Description = "Các ưu đãi và giảm giá",
                            Image = "/assets/img/product/small-product3.png",
                            Title = "Tin khuyến mại"
                        },
                        new
                        {
                            BlogCategoryId = 4,
                            Alias = "song",
                            CreatedDate = new DateTime(2026, 7, 28, 11, 57, 13, 892, DateTimeKind.Unspecified),
                            Description = "Lifestyle & tips",
                            Image = "/assets/img/product/small-product4.png",
                            Title = "Phong cách sống"
                        });
                });

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbBlogComment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"), 1L, 1);

                    b.Property<int?>("BlogId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("CommentId");

                    b.HasIndex("BlogId");

                    b.HasIndex("CustomerId");

                    b.ToTable("tb_BlogComment", (string)null);
                });

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbChatMessage", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"), 1L, 1);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("GuestToken")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("MessageId");

                    b.HasIndex("UserId");

                    b.ToTable("tb_ChatMessage", (string)null);
                });

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbColor", b =>
                {
                    b.Property<int>("ColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColorId"), 1L, 1);

                    b.Property<string>("ColorCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ColorName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("ColorId");

                    b.ToTable("tb_Color");

                    b.HasData(
                        new
                        {
                            ColorId = 1,
                            ColorCode = "#FFFFFF",
                            ColorName = "Trắng",
                            IsActive = true
                        },
                        new
                        {
                            ColorId = 2,
                            ColorCode = "#000000",
                            ColorName = "Đen",
                            IsActive = true
                        },
                        new
                        {
                            ColorId = 3,
                            ColorCode = "#808080",
                            ColorName = "Xám",
                            IsActive = true
                        },
                        new
                        {
                            ColorId = 4,
                            ColorCode = "#FF0000",
                            ColorName = "Đỏ",
                            IsActive = true
                        },
                        new
                        {
                            ColorId = 5,
                            ColorCode = "#0000FF",
                            ColorName = "Xanh dương",
                            IsActive = true
                        },
                        new
                        {
                            ColorId = 6,
                            ColorCode = "#00AA00",
                            ColorName = "Xanh lá",
                            IsActive = true
                        },
                        new
                        {
                            ColorId = 7,
                            ColorCode = "#FFFF00",
                            ColorName = "Vàng",
                            IsActive = true
                        },
                        new
                        {
                            ColorId = 8,
                            ColorCode = "#FFC0CB",
                            ColorName = "Hồng",
                            IsActive = true
                        },
                        new
                        {
                            ColorId = 9,
                            ColorCode = "#8B4513",
                            ColorName = "Nâu",
                            IsActive = true
                        },
                        new
                        {
                            ColorId = 10,
                            ColorCode = "#800080",
                            ColorName = "Tím",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbContact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"), 1L, 1);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ContactId");

                    b.ToTable("tb_Contact", (string)null);
                });

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbCustomer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"), 1L, 1);

                    b.Property<string>("Avatar")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CustomerId");

                    b.ToTable("tb_Customer");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Birthday = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "a@example.com",
                            IsActive = true,
                            LastLogin = new DateTime(2026, 7, 5, 7, 24, 31, 842, DateTimeKind.Unspecified),
                            Location = "Hanoi",
                            Name = "Nguyen Van A",
                            Password = "$2y$10$hash1",
                            Phone = "0901111001",
                            Username = "nguyena"
                        },
                        new
                        {
                            CustomerId = 2,
                            Birthday = new DateTime(1992, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "b@example.com",
                            IsActive = true,
                            LastLogin = new DateTime(2026, 7, 17, 18, 53, 46, 275, DateTimeKind.Unspecified),
                            Location = "HCMC",
                            Name = "Le Thi B",
                            Password = "$2y$10$hash2",
                            Phone = "0901111002",
                            Username = "lethib"
                        },
                        new
                        {
                            CustomerId = 3,
                            Birthday = new DateTime(1988, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "c@example.com",
                            IsActive = true,
                            LastLogin = new DateTime(2026, 7, 26, 22, 11, 8, 503, DateTimeKind.Unspecified),
                            Location = "Da Nang",
                            Name = "Tran Van C",
                            Password = "$2y$10$hash3",
                            Phone = "0901111003",
                            Username = "tranvc"
                        });
                });

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbMenu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuId"), 1L, 1);

                    b.Property<string>("Alias")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("Levels")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int?>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MenuId");

                    b.ToTable("tb_Menu");

                    b.HasData(
                        new
                        {
                            MenuId = 1,
                            Alias = "Home",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 7, 3, 8, 14, 25, 317, DateTimeKind.Unspecified),
                            Description = "Menu Trang chủ",
                            IsActive = true,
                            Levels = 1,
                            Position = 1,
                            Title = "Trang chủ"
                        },
                        new
                        {
                            MenuId = 2,
                            Alias = "Product",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 7, 7, 17, 42, 18, 904, DateTimeKind.Unspecified),
                            Description = "Menu Sản phẩm",
                            IsActive = true,
                            Levels = 1,
                            Position = 2,
                            Title = "Sản phẩm"
                        },
                        new
                        {
                            MenuId = 3,
                            Alias = "tin-tuc",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 7, 10, 21, 9, 56, 481, DateTimeKind.Unspecified),
                            Description = "Menu Tin tức",
                            IsActive = false,
                            Levels = 1,
                            Position = 3,
                            Title = "Tin tức"
                        },
                        new
                        {
                            MenuId = 4,
                            Alias = "Blog",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 7, 12, 11, 36, 43, 225, DateTimeKind.Unspecified),
                            Description = "Menu Blog",
                            IsActive = true,
                            Levels = 1,
                            Position = 4,
                            Title = "Bài viết"
                        },
                        new
                        {
                            MenuId = 5,
                            Alias = "About",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 7, 15, 9, 51, 7, 638, DateTimeKind.Unspecified),
                            Description = "Menu Giới thiệu",
                            IsActive = true,
                            Levels = 1,
                            Position = 5,
                            Title = "Giới thiệu"
                        },
                        new
                        {
                            MenuId = 6,
                            Alias = "Contact",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 7, 18, 14, 27, 31, 752, DateTimeKind.Unspecified),
                            Description = "Menu Liên hệ",
                            IsActive = true,
                            Levels = 1,
                            Position = 6,
                            Title = "Liên hệ"
                        },
                        new
                        {
                            MenuId = 7,
                            Alias = "khuyen-mai",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 7, 20, 20, 13, 49, 116, DateTimeKind.Unspecified),
                            Description = "Menu KM",
                            IsActive = true,
                            Levels = 2,
                            ParentId = 3,
                            Position = 1,
                            Title = "Khuyến mại"
                        },
                        new
                        {
                            MenuId = 8,
                            Alias = "nam",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 7, 23, 7, 45, 12, 593, DateTimeKind.Unspecified),
                            Description = "Danh mục nam",
                            IsActive = true,
                            Levels = 2,
                            ParentId = 2,
                            Position = 1,
                            Title = "Nam"
                        },
                        new
                        {
                            MenuId = 9,
                            Alias = "nu",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 7, 26, 16, 18, 54, 871, DateTimeKind.Unspecified),
                            Description = "Danh mục nữ",
                            IsActive = true,
                            Levels = 2,
                            ParentId = 2,
                            Position = 2,
                            Title = "Nữ"
                        },
                        new
                        {
                            MenuId = 10,
                            Alias = "the-thao",
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 7, 29, 23, 58, 36, 404, DateTimeKind.Unspecified),
                            Description = "Danh mục thể thao",
                            IsActive = true,
                            Levels = 2,
                            ParentId = 2,
                            Position = 3,
                            Title = "Thể thao"
                        });
                });

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"), 1L, 1);

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderStatusId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShippingAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderStatusId");

                    b.ToTable("tb_Order");
                });

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbOrderDetail", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("tb_OrderDetail");
                });

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbOrderStatus", b =>
                {
                    b.Property<int>("OrderStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderStatusId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OrderStatusId");

                    b.ToTable("tb_OrderStatus");

                    b.HasData(
                        new
                        {
                            OrderStatusId = 1,
                            Description = "Chờ xử lý",
                            Name = "Pending"
                        },
                        new
                        {
                            OrderStatusId = 3,
                            Description = "Đã xử lý",
                            Name = "Processing"
                        },
                        new
                        {
                            OrderStatusId = 4,
                            Description = "Đã gửi hàng",
                            Name = "Shipped"
                        },
                        new
                        {
                            OrderStatusId = 5,
                            Description = "Đã giao",
                            Name = "Delivered"
                        },
                        new
                        {
                            OrderStatusId = 6,
                            Description = "Đã hủy",
                            Name = "Canceled"
                        },
                        new
                        {
                            OrderStatusId = 7,
                            Description = "Đã hoàn tiền",
                            Name = "Refunded"
                        },
                        new
                        {
                            OrderStatusId = 9,
                            Description = "Trả hàng",
                            Name = "Returned"
                        },
                        new
                        {
                            OrderStatusId = 10,
                            Description = "Giao dịch thất bại",
                            Name = "Failed"
                        });
                });

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbProduct", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("Alias")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("CategoryProductId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBestSeller")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PriceSale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<double?>("Star")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryProductId");

                    b.ToTable("tb_Product");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Alias = "ao-thun-cotton-nam",
                            CategoryProductId = 1,
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 7, 3, 8, 15, 27, 416, DateTimeKind.Unspecified),
                            Description = "Áo thun cotton thoáng mát",
                            Image = "/assets/img/product/product1.png",
                            IsActive = true,
                            IsBestSeller = true,
                            IsNew = true,
                            Price = 250000.00m,
                            PriceSale = 199000.00m,
                            Quantity = 190,
                            Star = 5.0,
                            Title = "Áo thun cotton nam"
                        },
                        new
                        {
                            ProductId = 2,
                            Alias = "quan-jeans-nam",
                            CategoryProductId = 1,
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 7, 8, 17, 42, 51, 783, DateTimeKind.Unspecified),
                            Description = "Quần jeans co giãn",
                            Image = "/assets/img/product/product2.png",
                            IsActive = true,
                            IsBestSeller = true,
                            IsNew = false,
                            Price = 300000.00m,
                            PriceSale = 399000.00m,
                            Quantity = 210,
                            Star = 4.0,
                            Title = "Quần jeans nam"
                        },
                        new
                        {
                            ProductId = 3,
                            Alias = "dam-nu-maxi",
                            CategoryProductId = 2,
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 7, 14, 12, 36, 18, 592, DateTimeKind.Unspecified),
                            Description = "Đầm maxi nữ",
                            Image = "/assets/img/product/product3.png",
                            IsActive = true,
                            IsBestSeller = false,
                            IsNew = true,
                            Price = 550000.00m,
                            PriceSale = 499000.00m,
                            Quantity = 240,
                            Star = 5.0,
                            Title = "Đầm nữ maxi"
                        },
                        new
                        {
                            ProductId = 4,
                            Alias = "giay-sneakers",
                            CategoryProductId = 3,
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 7, 21, 20, 9, 45, 138, DateTimeKind.Unspecified),
                            Description = "Giày thể thao unisex",
                            Image = "/assets/img/product/product4.png",
                            IsActive = true,
                            IsBestSeller = true,
                            IsNew = false,
                            Price = 800000.00m,
                            PriceSale = 650000.00m,
                            Quantity = 330,
                            Star = 4.0,
                            Title = "Áo phông nữ"
                        },
                        new
                        {
                            ProductId = 5,
                            Alias = "tui-xach-da",
                            CategoryProductId = 4,
                            CreatedBy = "admin",
                            CreatedDate = new DateTime(2026, 7, 29, 9, 58, 12, 964, DateTimeKind.Unspecified),
                            Description = "Túi xách da thật",
                            Image = "/assets/img/product/product5.png",
                            IsActive = true,
                            IsBestSeller = false,
                            IsNew = false,
                            Price = 1200000.00m,
                            PriceSale = 999000.00m,
                            Quantity = 150,
                            Star = 5.0,
                            Title = "Áo khoác da"
                        });
                });

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbProductCategory", b =>
                {
                    b.Property<int>("CategoryProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryProductId"), 1L, 1);

                    b.Property<string>("Alias")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CategoryProductId");

                    b.ToTable("tb_ProductCategory");

                    b.HasData(
                        new
                        {
                            CategoryProductId = 1,
                            Alias = "thoi-trang-nam",
                            CreatedDate = new DateTime(2026, 7, 14, 8, 23, 17, 451, DateTimeKind.Unspecified),
                            Description = "Quần áo & phụ kiện dành cho nam",
                            Icon = "/assets/img/product/small-product1.png",
                            Position = 1,
                            Title = "Thời trang nam"
                        },
                        new
                        {
                            CategoryProductId = 2,
                            Alias = "thoi-trang-nu",
                            CreatedDate = new DateTime(2026, 7, 3, 19, 45, 52, 183, DateTimeKind.Unspecified),
                            Description = "Quần áo & phụ kiện dành cho nữ",
                            Icon = "/assets/img/product/small-product2.png",
                            Position = 2,
                            Title = "Áo sơ mi"
                        },
                        new
                        {
                            CategoryProductId = 3,
                            Alias = "giay-dep",
                            CreatedDate = new DateTime(2026, 7, 28, 13, 11, 36, 924, DateTimeKind.Unspecified),
                            Description = "Các loại giày dép",
                            Icon = "/assets/img/product/small-product3.png",
                            Position = 3,
                            Title = "Áo khoác"
                        },
                        new
                        {
                            CategoryProductId = 4,
                            Alias = "tui-xach",
                            CreatedDate = new DateTime(2026, 7, 9, 22, 58, 9, 615, DateTimeKind.Unspecified),
                            Description = "Túi xách thời trang",
                            Icon = "/assets/img/product/small-product4.png",
                            Position = 4,
                            Title = "Áo hoodie"
                        },
                        new
                        {
                            CategoryProductId = 5,
                            Alias = "phu-kien",
                            CreatedDate = new DateTime(2026, 7, 21, 5, 34, 41, 207, DateTimeKind.Unspecified),
                            Description = "Phụ kiện",
                            Icon = "/assets/img/product/small-product5.png",
                            Position = 5,
                            Title = "Áo polo"
                        },
                        new
                        {
                            CategoryProductId = 6,
                            Alias = "do-the-thao",
                            CreatedDate = new DateTime(2026, 7, 17, 16, 7, 58, 332, DateTimeKind.Unspecified),
                            Description = "Trang phục thể thao",
                            Icon = "/assets/img/product/small-product6.png",
                            Position = 6,
                            Title = "Áo len"
                        },
                        new
                        {
                            CategoryProductId = 7,
                            Alias = "do-tre-em",
                            CreatedDate = new DateTime(2026, 7, 30, 11, 52, 24, 786, DateTimeKind.Unspecified),
                            Description = "Sản phẩm cho trẻ em",
                            Icon = "/assets/img/product/small-product7.png",
                            Position = 7,
                            Title = "Áo cardigan"
                        },
                        new
                        {
                            CategoryProductId = 8,
                            Alias = "dien-tu",
                            CreatedDate = new DateTime(2026, 7, 12, 0, 16, 33, 549, DateTimeKind.Unspecified),
                            Description = "Phụ kiện điện tử",
                            Icon = "/assets/img/product/small-product8.png",
                            Position = 8,
                            Title = "Áo dài tay"
                        },
                        new
                        {
                            CategoryProductId = 9,
                            Alias = "sac-dep",
                            CreatedDate = new DateTime(2026, 7, 6, 21, 29, 14, 968, DateTimeKind.Unspecified),
                            Description = "Mỹ phẩm & chăm sóc",
                            Icon = "/assets/img/product/small-product9.png",
                            Position = 9,
                            Title = "Áo thể thao"
                        },
                        new
                        {
                            CategoryProductId = 10,
                            Alias = "nha-cua",
                            CreatedDate = new DateTime(2026, 7, 25, 9, 40, 27, 125, DateTimeKind.Unspecified),
                            Description = "Đồ dùng gia đình",
                            Icon = "/assets/img/product/small-product10.png",
                            Position = 10,
                            Title = "Áo vest"
                        });
                });

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbProductReview", b =>
                {
                    b.Property<int>("ProductReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductReviewId"), 1L, 1);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Star")
                        .HasColumnType("int");

                    b.HasKey("ProductReviewId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("tb_ProductReview");

                    b.HasData(
                        new
                        {
                            ProductReviewId = 1,
                            CreatedDate = new DateTime(2026, 7, 6, 10, 32, 19, 647, DateTimeKind.Unspecified),
                            CustomerId = 1,
                            Detail = "Sản phẩm tốt, chất lượng ổn.",
                            IsActive = true,
                            ProductId = 1,
                            Star = 5
                        },
                        new
                        {
                            ProductReviewId = 2,
                            CreatedDate = new DateTime(2026, 7, 19, 15, 47, 58, 114, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            Detail = "Vải mềm, giao hàng nhanh.",
                            IsActive = true,
                            ProductId = 1,
                            Star = 2
                        },
                        new
                        {
                            ProductReviewId = 3,
                            CreatedDate = new DateTime(2026, 7, 30, 21, 6, 42, 389, DateTimeKind.Unspecified),
                            CustomerId = 3,
                            Detail = "Form đẹp nhưng hơi chật.",
                            IsActive = true,
                            ProductId = 2,
                            Star = 4
                        });
                });

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbProductVariant", b =>
                {
                    b.Property<int>("VariantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VariantId"), 1L, 1);

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PriceSale")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("SizeId")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VariantId");

                    b.HasIndex("ColorId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SizeId");

                    b.ToTable("tb_ProductVariant");

                    b.HasData(
                        new
                        {
                            VariantId = 11,
                            ColorId = 1,
                            Image = "/files/product1.png",
                            IsActive = true,
                            Price = 250000.00m,
                            PriceSale = 199000.00m,
                            ProductId = 1,
                            Quantity = 40,
                            SizeId = 1,
                            Sku = "ATCN-DEN-S"
                        },
                        new
                        {
                            VariantId = 12,
                            ColorId = 1,
                            Image = "/files/big-product2.jpg",
                            IsActive = true,
                            Price = 250000.00m,
                            PriceSale = 199000.00m,
                            ProductId = 1,
                            Quantity = 35,
                            SizeId = 2,
                            Sku = "ATCN-DEN-M"
                        },
                        new
                        {
                            VariantId = 13,
                            ColorId = 1,
                            Image = "/files/big-product3.jpg",
                            IsActive = true,
                            Price = 250000.00m,
                            PriceSale = 199000.00m,
                            ProductId = 1,
                            Quantity = 30,
                            SizeId = 3,
                            Sku = "ATCN-DEN-L"
                        },
                        new
                        {
                            VariantId = 14,
                            ColorId = 3,
                            Image = "/files/big-product4.jpg",
                            IsActive = true,
                            Price = 250000.00m,
                            PriceSale = 199000.00m,
                            ProductId = 1,
                            Quantity = 45,
                            SizeId = 1,
                            Sku = "ATCN-TRANG-S"
                        },
                        new
                        {
                            VariantId = 15,
                            ColorId = 3,
                            Image = "/files/big-product5.jpg",
                            IsActive = true,
                            Price = 250000.00m,
                            PriceSale = 199000.00m,
                            ProductId = 1,
                            Quantity = 40,
                            SizeId = 2,
                            Sku = "ATCN-TRANG-M"
                        },
                        new
                        {
                            VariantId = 17,
                            ColorId = 1,
                            Image = "/files/product2.png",
                            IsActive = true,
                            Price = 300000.00m,
                            PriceSale = 399000.00m,
                            ProductId = 2,
                            Quantity = 40,
                            SizeId = 1,
                            Sku = "QJN-DEN-S"
                        },
                        new
                        {
                            VariantId = 18,
                            ColorId = 1,
                            Image = "/files/big-product4.jpg",
                            IsActive = true,
                            Price = 450000.00m,
                            PriceSale = 399000.00m,
                            ProductId = 2,
                            Quantity = 35,
                            SizeId = 2,
                            Sku = "QJN-DEN-M"
                        },
                        new
                        {
                            VariantId = 19,
                            ColorId = 1,
                            Image = "/files/product1.png",
                            IsActive = true,
                            Price = 450000.00m,
                            PriceSale = 399000.00m,
                            ProductId = 2,
                            Quantity = 30,
                            SizeId = 3,
                            Sku = "QJN-DEN-L"
                        },
                        new
                        {
                            VariantId = 20,
                            ColorId = 2,
                            Image = "/files/big-product4.jpg",
                            IsActive = true,
                            Price = 450000.00m,
                            PriceSale = 399000.00m,
                            ProductId = 2,
                            Quantity = 40,
                            SizeId = 1,
                            Sku = "QJN-XANH-S"
                        },
                        new
                        {
                            VariantId = 21,
                            ColorId = 2,
                            Image = "/files/big-product5.jpg",
                            IsActive = true,
                            Price = 450000.00m,
                            PriceSale = 399000.00m,
                            ProductId = 2,
                            Quantity = 35,
                            SizeId = 2,
                            Sku = "QJN-XANH-M"
                        });
                });

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RoleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId");

                    b.ToTable("tb_Role");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Description = "Quản trị",
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            Description = "Người bán hàng",
                            RoleName = "Seller"
                        });
                });

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbSize", b =>
                {
                    b.Property<int>("SizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SizeId"), 1L, 1);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SizeName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SizeOrder")
                        .HasColumnType("int");

                    b.HasKey("SizeId");

                    b.ToTable("tb_Size");

                    b.HasData(
                        new
                        {
                            SizeId = 1,
                            IsActive = true,
                            SizeName = "XS",
                            SizeOrder = 1
                        },
                        new
                        {
                            SizeId = 2,
                            IsActive = true,
                            SizeName = "S",
                            SizeOrder = 2
                        },
                        new
                        {
                            SizeId = 3,
                            IsActive = true,
                            SizeName = "M",
                            SizeOrder = 3
                        },
                        new
                        {
                            SizeId = 4,
                            IsActive = true,
                            SizeName = "L",
                            SizeOrder = 4
                        },
                        new
                        {
                            SizeId = 5,
                            IsActive = true,
                            SizeName = "XL",
                            SizeOrder = 5
                        },
                        new
                        {
                            SizeId = 6,
                            IsActive = true,
                            SizeName = "XXL",
                            SizeOrder = 6
                        },
                        new
                        {
                            SizeId = 7,
                            IsActive = true,
                            SizeName = "OneSize",
                            SizeOrder = 7
                        },
                        new
                        {
                            SizeId = 8,
                            IsActive = true,
                            SizeName = "36",
                            SizeOrder = 8
                        },
                        new
                        {
                            SizeId = 9,
                            IsActive = true,
                            SizeName = "37",
                            SizeOrder = 9
                        },
                        new
                        {
                            SizeId = 10,
                            IsActive = true,
                            SizeName = "38",
                            SizeOrder = 10
                        });
                });

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbAccount", b =>
                {
                    b.HasOne("San_Pham_Do_An1.Models.TbRole", "Role")
                        .WithMany("TbAccounts")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbBlog", b =>
                {
                    b.HasOne("San_Pham_Do_An1.Models.TbAccount", "Account")
                        .WithMany("TbBlogs")
                        .HasForeignKey("AccountId");

                    b.HasOne("San_Pham_Do_An1.Models.TbBlogCategory", "BlogCategory")
                        .WithMany("TbBlogs")
                        .HasForeignKey("BlogCategoryId");

                    b.Navigation("Account");

                    b.Navigation("BlogCategory");
                });

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbBlogComment", b =>
                {
                    b.HasOne("San_Pham_Do_An1.Models.TbBlog", "Blog")
                        .WithMany("TbBlogComments")
                        .HasForeignKey("BlogId");

                    b.HasOne("San_Pham_Do_An1.Models.TbCustomer", "Customer")
                        .WithMany("TbBlogComments")
                        .HasForeignKey("CustomerId");

                    b.Navigation("Blog");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbChatMessage", b =>
                {
                    b.HasOne("San_Pham_Do_An1.Models.TbAccount", "User")
                        .WithMany("TbChatMessages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbOrder", b =>
                {
                    b.HasOne("San_Pham_Do_An1.Models.TbCustomer", "Customer")
                        .WithMany("TbOrders")
                        .HasForeignKey("CustomerId");

                    b.HasOne("San_Pham_Do_An1.Models.TbOrderStatus", "OrderStatus")
                        .WithMany("TbOrders")
                        .HasForeignKey("OrderStatusId");

                    b.Navigation("Customer");

                    b.Navigation("OrderStatus");
                });

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbOrderDetail", b =>
                {
                    b.HasOne("San_Pham_Do_An1.Models.TbOrder", "Order")
                        .WithMany("TbOrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("San_Pham_Do_An1.Models.TbProduct", "Product")
                        .WithMany("TbOrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbProduct", b =>
                {
                    b.HasOne("San_Pham_Do_An1.Models.TbProductCategory", "CategoryProduct")
                        .WithMany("TbProducts")
                        .HasForeignKey("CategoryProductId");

                    b.Navigation("CategoryProduct");
                });

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbProductReview", b =>
                {
                    b.HasOne("San_Pham_Do_An1.Models.TbCustomer", "Customer")
                        .WithMany("TbProductReviews")
                        .HasForeignKey("CustomerId");

                    b.HasOne("San_Pham_Do_An1.Models.TbProduct", "Product")
                        .WithMany("TbProductReviews")
                        .HasForeignKey("ProductId");

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbProductVariant", b =>
                {
                    b.HasOne("San_Pham_Do_An1.Models.TbColor", "Color")
                        .WithMany("TbProductVariants")
                        .HasForeignKey("ColorId");

                    b.HasOne("San_Pham_Do_An1.Models.TbProduct", "Product")
                        .WithMany("TbProductVariants")
                        .HasForeignKey("ProductId");

                    b.HasOne("San_Pham_Do_An1.Models.TbSize", "Size")
                        .WithMany("TbProductVariants")
                        .HasForeignKey("SizeId");

                    b.Navigation("Color");

                    b.Navigation("Product");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbAccount", b =>
                {
                    b.Navigation("TbBlogs");

                    b.Navigation("TbChatMessages");
                });

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbBlog", b =>
                {
                    b.Navigation("TbBlogComments");
                });

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbBlogCategory", b =>
                {
                    b.Navigation("TbBlogs");
                });

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbColor", b =>
                {
                    b.Navigation("TbProductVariants");
                });

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbCustomer", b =>
                {
                    b.Navigation("TbBlogComments");

                    b.Navigation("TbOrders");

                    b.Navigation("TbProductReviews");
                });

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbOrder", b =>
                {
                    b.Navigation("TbOrderDetails");
                });

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbOrderStatus", b =>
                {
                    b.Navigation("TbOrders");
                });

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbProduct", b =>
                {
                    b.Navigation("TbOrderDetails");

                    b.Navigation("TbProductReviews");

                    b.Navigation("TbProductVariants");
                });

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbProductCategory", b =>
                {
                    b.Navigation("TbProducts");
                });

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbRole", b =>
                {
                    b.Navigation("TbAccounts");
                });

            modelBuilder.Entity("San_Pham_Do_An1.Models.TbSize", b =>
                {
                    b.Navigation("TbProductVariants");
                });
#pragma warning restore 612, 618
        }
    }
}
